apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggenerate
  labels:
    app: loggenerate
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: loggenerate
  template:
    metadata:
      labels:
        app: loggenerate
    spec:
      containers:
        - name: loggenerate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.loggeneratePort }}
          env:
            - name: GENERATOR_HOST
              value: {{ .Values.env.GENERATOR_HOST }}
            - name: GENERATOR_PORT
              value: "{{ .Values.env.GENERATOR_PORT }}"
            - name: GENERATOR_ALIVE_URL
              value: {{ .Values.env.GENERATOR_ALIVE_URL }}
            - name: GENERATOR_START_URL
              value: {{ .Values.env.GENERATOR_START_URL }}
            - name: PARSER_API
              value: {{ .Values.env.PARSER_API }}
            - name: GENERATOR_RATE
              value: "{{ .Values.env.GENERATOR_RATE }}"
            - name: GENERATOR_UNIT
              value: "{{ .Values.env.GENERATOR_UNIT }}"
