apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggenerate
  labels:
    app: loggenerate
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: loggenerate
  template:
    metadata:
      labels:
        app: loggenerate
    spec:
      containers:
        - name: loggenerate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.loggeneratePort }}
          env:
            - name: GENERATOR_HOST
              value: {{ .Values.env.GENERATOR_HOST }}
            - name: GENERATOR_PORT
              value: "{{ .Values.env.GENERATOR_PORT }}"
            - name: GENERATOR_ALIVE_URL
              value: {{ .Values.env.GENERATOR_ALIVE_URL }}
            - name: GENERATOR_START_URL
              value: {{ .Values.env.GENERATOR_START_URL }}
            - name: PARSER_API
              value: {{ .Values.env.PARSER_API }}
            - name: GENERATOR_RATE
              value: "{{ .Values.env.GENERATOR_RATE }}"
            - name: GENERATOR_UNIT
              value: "{{ .Values.env.GENERATOR_UNIT }}"



apiVersion: apps/v1
kind: Deployment
metadata:
  name: logparser
  labels:
    app: logparser
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: logparser
  template:
    metadata:
      labels:
        app: logparser
    spec:
      containers:
        - name: logparser
          image: "{{ .Values.logparserImage.repository }}:{{ .Values.logparserImage.tag }}"
          ports:
            - containerPort: {{ .Values.service.logparserPort }}
          env:
            - name: PARSER_HOST
              value: {{ .Values.env.PARSER_HOST }}
            - name: PARSER_PORT
              value: "{{ .Values.env.PARSER_PORT }}"
            - name: PARSER_ALIVE_URL
              value: {{ .Values.env.PARSER_ALIVE_URL }}
            - name: PARSER_ADD_URL
              value: {{ .Values.env.PARSER_ADD_URL }}
            - name: PARSER_GET_URL
              value: {{ .Values.env.PARSER_GET_URL }}
            - name: PARSER_GET_COUNT_URL
              value: {{ .Values.env.PARSER_GET_COUNT_URL }}
            - name: PARSER_DELETE_URL
              value: {{ .Values.env.PARSER_DELETE_URL }}
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST }}
            - name: DB_PORT
              value: "{{ .Values.env.DB_PORT }}"
            - name: DB_USERNAME
              value: {{ .Values.env.DB_USERNAME }}
            - name: DB_PASSWORD
              value: {{ .Values.env.DB_PASSWORD }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME }}
            - name: DB_SSLMODE
              value: {{ .Values.env.DB_SSLMODE }}



apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.db }}"
