apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'loggenerate'
        static_configs:
          - targets: ['loggenerate:8081']
      - job_name: 'logparser'
        static_configs:
          - targets: ['logparser:8082']
