apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.service.postgresPort }}
      targetPort: {{ .Values.service.postgresPort }}
