apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: {{ .Values.service.grafanaPort }}
      targetPort: {{ .Values.service.grafanaPort }}
