database:
  DB_PORT: "5432"
  DB_HOST: "postgres" #"postgres"  #"172.17.0.4"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "123456"
  DB_NAME: "logsdb"
  DB_SSLMODE: "disable"

logs:
  TABLE_NAME: "logs"
  CREATE_TABLE_QUERY: |
    CREATE TABLE IF NOT EXISTS logs (
      id SERIAL PRIMARY KEY,
      remote_addr VARCHAR(255),
      remote_user VARCHAR(255),
      time_local TIMESTAMPTZ,
      request VARCHAR(255),
      status INT,
      body_bytes_sent INT,
      http_referer VARCHAR(255),
      http_user_agent VARCHAR(255),
      http_x_forwarded_for VARCHAR(255)
    )
